### ISSUE TITLE
console.log doesn't work

### ISSUE THREAD

**Issue by tvoloshyn** [ShPelles/electron-schematics#11]
I've noticed that console.log doesn't seem to be outputing anything to the terminal when `ng serve electron` command is being used. From what I understand this is related to how electron is started (through process spawning in node).

Therefore, it would be good to pipe an output of child process to parent process when spawning electron
https://github.com/ShPelles/electron-schematics/blob/2a2b1c1cb10c2e8efb78b04d9b16711b59bd14ad/packages/build-electron/src/start/index.ts#L61

For example: `proc.spawn(electron, [projectRoot, '--serve'], {stdio: ['pipe', process.stdout, process.stderr]});`

**Comment by eranshmil** [comment]
@ShPelles Please publish a new version with this fix.

**Comment by ShPelles** [comment]
Done.
