### ISSUE TITLE
Multiple processes after uncaught exceptions

### ISSUE THREAD

**Issue by eranshmil** [ShPelles/electron-schematics#18]
## Description

![image](https://user-images.githubusercontent.com/9721664/48893167-5c655180-ee48-11e8-9b7c-4dc7cfab0e67.png)
Electron is not being killed all of the time.

## Expected Behavior
The task must be killed every time.

## Actual Behavior
Most of the time, when there is a runtime error, the task is not being killed but a new one is opened.

## Possible Fix
Add 'SIGKILL' to tree kill command.
PR: #19 

## Steps to Reproduce

1. Run with ng serve.
1. Create a runtime error and leave the alert message opened.
1. Fix the runtime error and most of the time there will be an old task that can't be closed without kill command.

## Context
After working a few hours on the project, there are too much opened tasks and I had to kill them all using the activity monitor (aka task manager).

## Your Environment

- Version used: v0.6.0
- Operating System and version (desktop or mobile): macOS 10.13.6 (High Sierra)
- NodeJS version: v8.12.0
- Electron version: v3.0.9
- NPM/Yarn version: v1.12.3

**Comment by ShPelles** [comment]
Is it reproduced in version 0.6.5?

**Comment by eranshmil** [comment]
Yeah.
I hoped it will fix that issue.
So after I upgraded to 0.6.5, I changed this line directly in the node_modules folder and it seems to work just fine. (At least, under macOS)

**Comment by eranshmil** [comment]
@ShPelles Could you have a look?

**Comment by eranshmil** [comment]
Resolved in #19.
