### ISSUE TITLE
Not able to reference assets in production

### ISSUE THREAD

**Issue by pontusr** [ShPelles/electron-schematics#32]
## Description
Because the baseHref is not set to './' the bundled build will not be able to reference assets in the app.asar.

## Expected Behavior
References in angular templates in the related web project to for example 'assets/image.png' should resolve correctly also in the bundled app produced by electron-builder.

## Actual Behavior
Electron will try to find the assets at 'index.html/assets/image.png' which obviously produces a 404.

## Possible Fix
https://github.com/ShPelles/electron-schematics/pull/29

## Steps to Reproduce
1. `npm install -g @angular/cli`
2. `ng new my-dream-app`
3. `cd my-dream-app`
4. `ng add @electron-schematics/schematics`
5. Place image.png in /src/assets
6. Add `<img src="assets/image.png">` to /src/app/app.component.html
7. `ng build electron`
8. Execute /dist/electron Setup 0.0.1.[exe, dmg, AppImage] (installer for your OS)
9. Open devtools and verify the cause of the issue.

## Context
We need to be able to reuse reference to asssets in the web project without modification.

## Your Environment
- Version used: 0.7.0
Across Mac/Windows/Linux

**Comment by ShPelles** [comment]
Closing. Fixed by #29
